"""Deterministic frozen-seed replication for native contest arms."""

from __future__ import annotations

from typing import TYPE_CHECKING, Callable, Mapping, Optional

import torch

from dagua.layout.ops.pipelines.native_budget import admit_native_work
from dagua.layout.ops.pipelines.native_contest_cascade import select_finalists
from dagua.layout.ops.pipelines.native_cost_model import NativeWorkCost

if TYPE_CHECKING:  # pragma: no cover - typing only
    from dagua.config import LayoutConfig

# Offsets are frozen protocol data, not samples drawn from the graph RNG. The
# first three preserve the marketplace's historical adjacent-seed coverage;
# the wider final offsets explore distinct basins without graph-specific fit.
FROZEN_CONTEST_SEED_OFFSETS: tuple[int, ...] = (0, 1, 2, 17, 43)
DEFAULT_STOCHASTIC_SEED_COUNT = len(FROZEN_CONTEST_SEED_OFFSETS)
SEED_REPLICA_FINALISTS_PER_FAMILY = 2
SEED_COUNT_OVERRIDE_ATTR = "_dagua_native_stochastic_seed_count"
_FALLBACK_SEED_COUNTS = (3, 1)


def frozen_seed_bank(
    config: Optional["LayoutConfig"],
    base_seed: int,
) -> tuple[int, ...]:
    """Return the configured prefix of the frozen contest seed bank.

    Parameters
    ----------
    config : LayoutConfig, optional
        Native configuration. Tests and attribution runs may set
        ``_dagua_native_stochastic_seed_count`` to force ``k=1``.
    base_seed : int
        Existing arm seed. The first returned seed is exactly this value.

    Returns
    -------
    tuple[int, ...]
        One to five deterministic absolute seeds.
    """
    requested = int(getattr(config, SEED_COUNT_OVERRIDE_ATTR, DEFAULT_STOCHASTIC_SEED_COUNT))
    count = min(len(FROZEN_CONTEST_SEED_OFFSETS), max(1, requested))
    return tuple(int(base_seed) + offset for offset in FROZEN_CONTEST_SEED_OFFSETS[:count])


def replicated_work_cost(
    base_cost: NativeWorkCost,
    seed_count: int,
    finalist_count: int = SEED_REPLICA_FINALISTS_PER_FAMILY,
) -> NativeWorkCost:
    """Return one all-or-nothing ledger package for a replicated arm family.

    Parameters
    ----------
    base_cost : NativeWorkCost
        Modeled generation and referee cost for one seed.
    seed_count : int
        Number of seed replicas generated by the family.
    finalist_count : int, default=2
        Maximum replicas retained for the honest referee.

    Returns
    -------
    NativeWorkCost
        Aggregate generation cost for all seeds and score reserve for only the
        proxy-cull finalists.
    """
    count = max(1, int(seed_count))
    scored = min(count, max(1, int(finalist_count)))
    metadata = dict(base_cost.metadata)
    metadata.update({"seed_count": count, "seed_finalist_count": scored})
    return NativeWorkCost(
        family=base_cost.family,
        generation_dwu=float(base_cost.generation_dwu) * count,
        reserved_score_dwu=float(base_cost.reserved_score_dwu) * scored,
        metadata=metadata,
        mandatory_tail_dwu=float(base_cost.mandatory_tail_dwu),
        device_class=base_cost.device_class,
    )


def admit_seed_family(
    config: Optional["LayoutConfig"],
    base_cost: NativeWorkCost,
    family: str,
    seeds: tuple[int, ...],
    work_count: Optional[int] = None,
    package_gate: Optional[Callable[[NativeWorkCost], bool]] = None,
    ledger_reason: Optional[str] = None,
) -> tuple[int, ...]:
    """Admit the largest affordable frozen prefix as one ledger decision.

    Parameters
    ----------
    config : LayoutConfig, optional
        Native configuration carrying the deterministic ledger.
    base_cost : NativeWorkCost
        Modeled cost for one seed.
    family : str
        Stable arm-family label used in the ledger reason.
    seeds : tuple[int, ...]
        Frozen seeds that must run together or not at all.
    work_count : int, optional
        Total family trajectories when each frozen seed is combined with a
        fixed parameter grid. Defaults to the number of seeds.
    package_gate : callable, optional
        Additional deterministic admission predicate applied to each complete
        prefix package before consulting the ledger.
    ledger_reason : str, optional
        Exact ledger reason. Defaults to ``optional_seed_family_<family>``.

    Returns
    -------
    tuple[int, ...]
        Admitted frozen prefix. An empty tuple means even the pre-packet base
        arm was rejected.
    """
    if not seeds:
        raise ValueError("seeds must not be empty")
    total_trajectories = len(seeds) if work_count is None else max(len(seeds), int(work_count))
    candidate_counts = [len(seeds)]
    candidate_counts.extend(count for count in _FALLBACK_SEED_COUNTS if count < len(seeds))
    for seed_count in candidate_counts:
        # Parameter grids scale with the chosen seed prefix (for example,
        # tsNET runs two fixed perplexities for every admitted seed).
        trajectory_count = max(
            seed_count,
            (total_trajectories * seed_count + len(seeds) - 1) // len(seeds),
        )
        package = replicated_work_cost(base_cost, trajectory_count)
        package.metadata["seed_count"] = seed_count
        package.metadata["trajectory_count"] = trajectory_count
        if package_gate is not None and not package_gate(package):
            continue
        reason = ledger_reason or f"optional_seed_family_{family}"
        if admit_native_work(config, package, reason):
            return seeds[:seed_count]
    return ()


def retained_seed_replicas(
    candidates: Mapping[str, torch.Tensor],
    proxy_scores: Mapping[str, float],
    replicated_families: Mapping[str, str],
    finalists_per_family: int = SEED_REPLICA_FINALISTS_PER_FAMILY,
) -> set[str]:
    """Return candidates retained after within-family W1-C proxy culls.

    Parameters
    ----------
    candidates : Mapping[str, torch.Tensor]
        All contest candidates with positions shaped ``[N, 2]``.
    proxy_scores : Mapping[str, float]
        Cheap higher-is-better proxy score for every candidate.
    replicated_families : Mapping[str, str]
        Replica candidate names mapped to stochastic family labels. Candidates
        absent from this mapping are deterministic or legacy single shots.
    finalists_per_family : int, default=2
        Maximum candidates retained from each replicated family.

    Returns
    -------
    set[str]
        Names to keep. Non-replicated candidates are always included.

    Raises
    ------
    ValueError
        If a replica mapping names an unknown candidate.
    """
    unknown = set(replicated_families) - set(candidates)
    if unknown:
        raise ValueError(f"unknown replicated candidate names: {sorted(unknown)}")
    if finalists_per_family <= 0:
        raise ValueError("finalists_per_family must be positive")
    retained = set(candidates) - set(replicated_families)
    for family in sorted(set(replicated_families.values())):
        names = sorted(
            name
            for name, candidate_family in replicated_families.items()
            if candidate_family == family
        )
        if len(names) <= finalists_per_family:
            retained.update(names)
            continue
        family_candidates = {name: candidates[name] for name in names}
        family_proxy_scores = {name: proxy_scores[name] for name in names}
        raw_names = [name for name in names if name.endswith("_raw")]
        if raw_names:
            best_raw = min(raw_names, key=lambda name: (-family_proxy_scores[name], name))
            retained.add(best_raw)
            family_candidates = {
                name: candidate
                for name, candidate in family_candidates.items()
                if name not in raw_names
            }
            family_proxy_scores = {
                name: score for name, score in family_proxy_scores.items() if name not in raw_names
            }
        remaining_slots = finalists_per_family - int(bool(raw_names))
        if remaining_slots == 0 or not family_candidates:
            continue
        retained.update(
            select_finalists(
                family_candidates,
                family_proxy_scores,
                {},
                remaining_slots,
                [],
            )
        )
    return retained


__all__ = [
    "DEFAULT_STOCHASTIC_SEED_COUNT",
    "FROZEN_CONTEST_SEED_OFFSETS",
    "SEED_COUNT_OVERRIDE_ATTR",
    "SEED_REPLICA_FINALISTS_PER_FAMILY",
    "admit_seed_family",
    "frozen_seed_bank",
    "replicated_work_cost",
    "retained_seed_replicas",
]
