#!/usr/bin/env python3
"""Compare reimplementation layouts against original competitor layouts.

Computes layout similarity (Procrustes, distance correlation, k-NN preservation),
quality metrics, and statistical tests for stochastic algorithms. Generates a
PDF report summarizing faithfulness of each reimplementation.

Usage:
    python scripts/compare_reimpl_vs_original.py
    python scripts/compare_reimpl_vs_original.py --ground-truth eval_output/ground_truth
    python scripts/compare_reimpl_vs_original.py --reimpl eval_output/reimpl_layouts
    python scripts/compare_reimpl_vs_original.py --report eval_output/reimpl_comparison_report.pdf

Prerequisites:
    - Ground truth layouts generated by scripts/generate_ground_truth.py
    - Reimplementation layouts generated by scripts/generate_reimpl_layouts.py
"""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import torch

# ─── Pairing configuration ───────────────────────────────────────────────────

# Maps reimplementation name -> list of original competitor names to compare against
# Primary comparison is first; secondary comparisons are algorithmic relatives
REIMPL_TO_ORIGINALS = {
    "classic_fr": ["nx_spring", "igraph_fr"],
    "classic_kk": ["nx_kamada_kawai", "igraph_kamada_kawai"],
    "classic_fa2": ["fa2_ref"],
    "classic_gem": ["ogdf_gem"],
    "classic_stress_sgd": ["sgd2"],
    "classic_maxent_stress": ["ogdf_stress"],
    "classic_spectral": ["nx_spectral"],
    "classic_pivot_mds": ["ogdf_pivot_mds", "sgd2_mds", "igraph_mds"],
    "classic_sugiyama": ["graphviz_dot", "igraph_sugiyama"],
    "classic_tsnet": ["tsne_graph"],  # closest proxy (vanilla t-SNE, not full tsNET loss)
    "classic_davidson_harel": ["igraph_davidson_harel", "ogdf_davidson_harel"],
    "classic_linlog": ["ogdf_linlog"],
    "classic_fmmm": ["ogdf_fmmm"],
}


# ─── Data structures ─────────────────────────────────────────────────────────


@dataclass
class PairwiseComparison:
    """Result of comparing two layouts of the same graph."""

    graph_name: str
    reimpl_name: str
    original_name: str
    reimpl_seed: Optional[int]
    original_seed: Optional[int]
    procrustes_disparity: float
    procrustes_similarity: float
    pairwise_distance_correlation: float
    knn_preservation: float
    comparison_type: str  # "reimpl_vs_original", "original_vs_original", "reimpl_vs_reimpl"


@dataclass
class MetricComparison:
    """Comparison of layout quality metrics between reimpl and original."""

    graph_name: str
    reimpl_name: str
    original_name: str
    reimpl_metrics: Dict[str, float]
    original_metrics: Dict[str, float]
    metric_deltas: Dict[str, float]  # reimpl - original


@dataclass
class AlgorithmReport:
    """Summary report for one reimplementation vs its original(s)."""

    reimpl_name: str
    original_names: List[str]
    num_graphs: int
    num_comparisons: int

    # Aggregated similarity (mean across all graphs)
    mean_procrustes_similarity: float
    mean_distance_correlation: float
    mean_knn_preservation: float

    # For stochastic: within-type vs between-type similarity
    mean_within_original_similarity: float  # original seeds vs each other
    mean_within_reimpl_similarity: float  # reimpl seeds vs each other
    mean_between_similarity: float  # reimpl vs original across seeds
    # Statistical test: is between-similarity >= within-similarity?
    similarity_ratio: float  # between / min(within_original, within_reimpl)

    # Metric comparison
    mean_metric_deltas: Dict[str, float]

    # Per-graph details
    per_graph_similarities: Dict[str, float] = field(default_factory=dict)
    failures: List[str] = field(default_factory=list)


# ─── Core comparison functions ───────────────────────────────────────────────


def _load_positions(path: Path) -> Optional[torch.Tensor]:
    """Load a position tensor from a .pt file."""
    try:
        pos = torch.load(path, map_location="cpu")
        if isinstance(pos, torch.Tensor) and pos.ndim == 2 and pos.shape[1] == 2:
            return pos
    except Exception:
        pass
    return None


def _compute_similarity(pos_a: torch.Tensor, pos_b: torch.Tensor) -> Dict[str, float]:
    """Compute layout similarity metrics between two position tensors."""
    from dagua.metrics import layout_similarity

    return layout_similarity(pos_a, pos_b)


def _compute_metrics(
    pos: torch.Tensor, edge_index: torch.Tensor, node_sizes: torch.Tensor
) -> Dict[str, float]:
    """Compute layout quality metrics."""
    from dagua.metrics import quick

    return quick(pos, edge_index, node_sizes=node_sizes)


def _find_layout_files(directory: Path, name_prefix: str) -> List[Tuple[Path, Optional[int]]]:
    """Find all layout files matching a prefix. Returns (path, seed) pairs."""
    results = []
    for f in sorted(directory.glob(f"{name_prefix}*.pt")):
        fname = f.stem
        if "_seed" in fname:
            seed = int(fname.split("_seed")[-1])
            results.append((f, seed))
        elif fname == name_prefix:
            results.append((f, None))
    return results


# ─── Main comparison pipeline ────────────────────────────────────────────────


def compare_all(
    gt_dir: Path,
    reimpl_dir: Path,
    output_dir: Path,
    max_graphs: int = 0,
) -> List[AlgorithmReport]:
    """Run the full comparison pipeline.

    Parameters
    ----------
    gt_dir : Path
        Directory with ground truth layouts (from generate_ground_truth.py).
    reimpl_dir : Path
        Directory with reimplementation layouts (from generate_reimpl_layouts.py).
    output_dir : Path
        Directory for comparison results.
    max_graphs : int
        Limit number of graphs to process (0 = all).

    Returns
    -------
    list of AlgorithmReport
        One report per reimplementation algorithm.
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    # Load manifests
    gt_manifest = json.loads((gt_dir / "manifest.json").read_text())
    reimpl_manifest = json.loads((reimpl_dir / "manifest.json").read_text())

    # Get graph names from both manifests
    gt_graphs = {g["graph_name"]: g for g in gt_manifest["graphs"]}
    reimpl_graphs = {r["graph_name"] for r in reimpl_manifest["records"] if r["success"]}
    common_graphs = sorted(set(gt_graphs.keys()) & reimpl_graphs)

    if max_graphs > 0:
        common_graphs = common_graphs[:max_graphs]

    print(f"Comparing {len(common_graphs)} graphs")
    print(f"Ground truth dir: {gt_dir}")
    print(f"Reimpl dir: {reimpl_dir}")

    # Load graph structures for metric computation
    from dagua.eval.graphs import get_test_graphs

    test_graphs = {tg.name: tg for tg in get_test_graphs(max_nodes=10000)}

    # Process each reimplementation
    all_reports = []
    all_comparisons = []
    all_metric_comparisons = []

    for reimpl_name, original_names in REIMPL_TO_ORIGINALS.items():
        print(f"\n{'=' * 60}")
        print(f"Reimplementation: {reimpl_name}")
        print(f"Original comparisons: {original_names or ['(quality metrics only)']}")
        print(f"{'=' * 60}")

        graph_similarities = {}
        graph_comparisons = []
        graph_metric_comps = []
        within_original_sims = []
        within_reimpl_sims = []
        between_sims = []
        metric_deltas_accum = defaultdict(list)
        failures = []

        for graph_name in common_graphs:
            if graph_name not in test_graphs:
                continue

            tg = test_graphs[graph_name]
            graph = tg.graph
            graph.compute_node_sizes()
            edge_index = graph.edge_index
            node_sizes = graph.node_sizes or torch.full((graph.num_nodes, 2), 20.0)

            gt_graph_dir = gt_dir / graph_name.replace(" ", "_").replace("/", "_")
            reimpl_graph_dir = reimpl_dir / graph_name.replace(" ", "_").replace("/", "_")

            if not gt_graph_dir.exists() or not reimpl_graph_dir.exists():
                continue

            # Load reimpl layouts
            reimpl_files = _find_layout_files(reimpl_graph_dir, reimpl_name)
            if not reimpl_files:
                failures.append(f"{graph_name}: no reimpl layouts found")
                continue

            reimpl_positions = []
            for path, seed in reimpl_files:
                pos = _load_positions(path)
                if pos is not None and pos.shape[0] == graph.num_nodes:
                    reimpl_positions.append((pos, seed))

            if not reimpl_positions:
                failures.append(f"{graph_name}: no valid reimpl positions")
                continue

            # Compute reimpl metrics
            reimpl_metrics = _compute_metrics(reimpl_positions[0][0], edge_index, node_sizes)

            # Compare against each original
            for orig_name in original_names:
                orig_files = _find_layout_files(gt_graph_dir, orig_name)
                if not orig_files:
                    continue

                orig_positions = []
                for path, seed in orig_files:
                    pos = _load_positions(path)
                    if pos is not None and pos.shape[0] == graph.num_nodes:
                        orig_positions.append((pos, seed))

                if not orig_positions:
                    continue

                # Original metrics
                orig_metrics = _compute_metrics(orig_positions[0][0], edge_index, node_sizes)

                # Metric deltas
                deltas = {}
                for key in set(reimpl_metrics.keys()) & set(orig_metrics.keys()):
                    try:
                        deltas[key] = float(reimpl_metrics[key]) - float(orig_metrics[key])
                        metric_deltas_accum[key].append(deltas[key])
                    except (TypeError, ValueError):
                        pass

                graph_metric_comps.append(
                    MetricComparison(
                        graph_name=graph_name,
                        reimpl_name=reimpl_name,
                        original_name=orig_name,
                        reimpl_metrics=reimpl_metrics,
                        original_metrics=orig_metrics,
                        metric_deltas=deltas,
                    )
                )

                # Pairwise similarity: reimpl vs original (between-type)
                for reimpl_pos, reimpl_seed in reimpl_positions:
                    for orig_pos, orig_seed in orig_positions:
                        sim = _compute_similarity(reimpl_pos, orig_pos)
                        comp = PairwiseComparison(
                            graph_name=graph_name,
                            reimpl_name=reimpl_name,
                            original_name=orig_name,
                            reimpl_seed=reimpl_seed,
                            original_seed=orig_seed,
                            procrustes_disparity=sim.get("procrustes_disparity", 1.0),
                            procrustes_similarity=sim.get("procrustes_similarity", 0.0),
                            pairwise_distance_correlation=sim.get(
                                "pairwise_distance_correlation", 0.0
                            ),
                            knn_preservation=sim.get("knn_preservation", 0.0),
                            comparison_type="reimpl_vs_original",
                        )
                        graph_comparisons.append(comp)
                        between_sims.append(comp.procrustes_similarity)

                # Within-original similarity (original seeds vs each other)
                if len(orig_positions) > 1:
                    for i in range(len(orig_positions)):
                        for j in range(i + 1, len(orig_positions)):
                            sim = _compute_similarity(orig_positions[i][0], orig_positions[j][0])
                            within_original_sims.append(sim.get("procrustes_similarity", 0.0))

                # Within-reimpl similarity (reimpl seeds vs each other)
                if len(reimpl_positions) > 1:
                    for i in range(len(reimpl_positions)):
                        for j in range(i + 1, len(reimpl_positions)):
                            sim = _compute_similarity(
                                reimpl_positions[i][0], reimpl_positions[j][0]
                            )
                            within_reimpl_sims.append(sim.get("procrustes_similarity", 0.0))

            # Per-graph aggregate similarity
            graph_sims = [
                c.procrustes_similarity for c in graph_comparisons if c.graph_name == graph_name
            ]
            if graph_sims:
                graph_similarities[graph_name] = sum(graph_sims) / len(graph_sims)

            print(
                f"  {graph_name}: {len(reimpl_positions)} reimpl, "
                f"sim={graph_similarities.get(graph_name, 'N/A')}"
            )

        # Build report
        all_between = between_sims or [0.0]
        all_within_orig = within_original_sims or [0.0]
        all_within_reimpl = within_reimpl_sims or [0.0]
        min_within = (
            min(
                sum(all_within_orig) / len(all_within_orig),
                sum(all_within_reimpl) / len(all_within_reimpl),
            )
            if all_within_orig and all_within_reimpl
            else 0.001
        )

        mean_deltas = {k: sum(v) / len(v) for k, v in metric_deltas_accum.items()}

        all_proc_sims = [c.procrustes_similarity for c in graph_comparisons]
        all_dist_corrs = [c.pairwise_distance_correlation for c in graph_comparisons]
        all_knn = [c.knn_preservation for c in graph_comparisons]

        report = AlgorithmReport(
            reimpl_name=reimpl_name,
            original_names=original_names,
            num_graphs=len(graph_similarities),
            num_comparisons=len(graph_comparisons),
            mean_procrustes_similarity=sum(all_proc_sims) / max(len(all_proc_sims), 1),
            mean_distance_correlation=sum(all_dist_corrs) / max(len(all_dist_corrs), 1),
            mean_knn_preservation=sum(all_knn) / max(len(all_knn), 1),
            mean_within_original_similarity=sum(all_within_orig) / max(len(all_within_orig), 1),
            mean_within_reimpl_similarity=sum(all_within_reimpl) / max(len(all_within_reimpl), 1),
            mean_between_similarity=sum(all_between) / max(len(all_between), 1),
            similarity_ratio=sum(all_between) / max(len(all_between), 1) / max(min_within, 0.001),
            mean_metric_deltas=mean_deltas,
            per_graph_similarities=graph_similarities,
            failures=failures,
        )
        all_reports.append(report)
        all_comparisons.extend(graph_comparisons)
        all_metric_comparisons.extend(graph_metric_comps)

        print(
            f"\n  Summary: {report.num_comparisons} comparisons, "
            f"mean similarity={report.mean_procrustes_similarity:.3f}"
        )
        if report.mean_within_original_similarity > 0:
            print(f"  Within-original: {report.mean_within_original_similarity:.3f}")
            print(f"  Within-reimpl:   {report.mean_within_reimpl_similarity:.3f}")
            print(f"  Between:         {report.mean_between_similarity:.3f}")
            print(f"  Ratio (between/min_within): {report.similarity_ratio:.3f}")

    # Save detailed results
    results = {
        "settings": {
            "gt_dir": str(gt_dir),
            "reimpl_dir": str(reimpl_dir),
            "num_graphs": len(common_graphs),
        },
        "reports": [
            {
                "reimpl": r.reimpl_name,
                "originals": r.original_names,
                "num_graphs": r.num_graphs,
                "num_comparisons": r.num_comparisons,
                "mean_procrustes_similarity": r.mean_procrustes_similarity,
                "mean_distance_correlation": r.mean_distance_correlation,
                "mean_knn_preservation": r.mean_knn_preservation,
                "within_original_sim": r.mean_within_original_similarity,
                "within_reimpl_sim": r.mean_within_reimpl_similarity,
                "between_sim": r.mean_between_similarity,
                "similarity_ratio": r.similarity_ratio,
                "mean_metric_deltas": r.mean_metric_deltas,
                "per_graph": r.per_graph_similarities,
                "failures": r.failures,
            }
            for r in all_reports
        ],
        "pairwise_comparisons": [
            {
                "graph": c.graph_name,
                "reimpl": c.reimpl_name,
                "original": c.original_name,
                "reimpl_seed": c.reimpl_seed,
                "original_seed": c.original_seed,
                "procrustes_similarity": c.procrustes_similarity,
                "distance_correlation": c.pairwise_distance_correlation,
                "knn_preservation": c.knn_preservation,
                "type": c.comparison_type,
            }
            for c in all_comparisons
        ],
    }

    results_path = output_dir / "comparison_results.json"
    with open(results_path, "w") as f:
        json.dump(results, f, indent=2, default=str)
    print(f"\nResults saved to {results_path}")

    # Generate PDF report
    _generate_pdf_report(all_reports, all_comparisons, output_dir)

    return all_reports


def _generate_pdf_report(
    reports: List[AlgorithmReport],
    comparisons: List[PairwiseComparison],
    output_dir: Path,
) -> None:
    """Generate a PDF summary report."""
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        from matplotlib.backends.backend_pdf import PdfPages
    except ImportError:
        print("matplotlib not available, skipping PDF report")
        return

    pdf_path = output_dir / "reimpl_comparison_report.pdf"

    with PdfPages(str(pdf_path)) as pdf:
        # Title page
        fig, ax = plt.subplots(figsize=(11, 8.5))
        ax.axis("off")
        ax.text(
            0.5,
            0.7,
            "Reimplementation Faithfulness Report",
            ha="center",
            va="center",
            fontsize=24,
            fontweight="bold",
        )
        ax.text(
            0.5, 0.5, f"{len(reports)} algorithms compared", ha="center", va="center", fontsize=16
        )
        ax.text(
            0.5,
            0.4,
            f"{sum(r.num_comparisons for r in reports)} total pairwise comparisons",
            ha="center",
            va="center",
            fontsize=14,
            color="gray",
        )
        pdf.savefig(fig)
        plt.close()

        # Summary table
        fig, ax = plt.subplots(figsize=(11, 8.5))
        ax.axis("off")

        table_data = []
        headers = [
            "Algorithm",
            "Originals",
            "Graphs",
            "Procrustes\nSimilarity",
            "Distance\nCorrelation",
            "k-NN\nPreservation",
            "Ratio\n(B/W)",
        ]

        for r in reports:
            orig_str = ", ".join(r.original_names) if r.original_names else "—"
            table_data.append(
                [
                    r.reimpl_name,
                    orig_str[:20],
                    str(r.num_graphs),
                    f"{r.mean_procrustes_similarity:.3f}",
                    f"{r.mean_distance_correlation:.3f}",
                    f"{r.mean_knn_preservation:.3f}",
                    f"{r.similarity_ratio:.2f}" if r.similarity_ratio > 0 else "—",
                ]
            )

        if table_data:
            table = ax.table(cellText=table_data, colLabels=headers, cellLoc="center", loc="center")
            table.auto_set_font_size(False)
            table.set_fontsize(8)
            table.scale(1.0, 1.5)

            # Color code similarity
            for i, row in enumerate(table_data):
                try:
                    sim = float(row[3])
                    color = (
                        (0.2, 0.8, 0.2, 0.3)
                        if sim > 0.8
                        else (1.0, 1.0, 0.0, 0.3)
                        if sim > 0.5
                        else (1.0, 0.3, 0.3, 0.3)
                    )
                    table[i + 1, 3].set_facecolor(color)
                except (ValueError, IndexError):
                    pass

        ax.set_title("Summary: Reimplementation Faithfulness", fontsize=16, pad=20)
        pdf.savefig(fig)
        plt.close()

        # Per-algorithm detail pages
        for report in reports:
            if not report.per_graph_similarities:
                continue

            fig, axes = plt.subplots(1, 2, figsize=(11, 5))

            # Left: per-graph similarity
            graphs = list(report.per_graph_similarities.keys())
            sims = list(report.per_graph_similarities.values())
            if graphs:
                short_names = [g[:15] for g in graphs]
                axes[0].barh(short_names, sims, color="steelblue")
                axes[0].set_xlim(0, 1)
                axes[0].set_xlabel("Procrustes Similarity")
                axes[0].set_title(f"{report.reimpl_name}\nPer-graph Similarity")
                axes[0].axvline(0.8, color="green", linestyle="--", alpha=0.5, label="Good (0.8)")
                axes[0].axvline(0.5, color="orange", linestyle="--", alpha=0.5, label="Fair (0.5)")
                axes[0].legend(fontsize=7)

            # Right: within vs between similarity (stochastic)
            if report.mean_within_original_similarity > 0:
                categories = ["Within\nOriginal", "Within\nReimpl", "Between\n(R vs O)"]
                values = [
                    report.mean_within_original_similarity,
                    report.mean_within_reimpl_similarity,
                    report.mean_between_similarity,
                ]
                colors = ["#4CAF50", "#2196F3", "#FF9800"]
                axes[1].bar(categories, values, color=colors)
                axes[1].set_ylim(0, 1)
                axes[1].set_ylabel("Mean Procrustes Similarity")
                axes[1].set_title("Stochastic Consistency\n(Between should ≈ Within)")
            else:
                axes[1].text(
                    0.5,
                    0.5,
                    "Deterministic algorithm\n(single comparison per graph)",
                    ha="center",
                    va="center",
                    fontsize=12,
                )
                axes[1].axis("off")

            plt.tight_layout()
            pdf.savefig(fig)
            plt.close()

    print(f"PDF report saved to {pdf_path}")


# ─── CLI ─────────────────────────────────────────────────────────────────────


def main():
    """Run the comparison pipeline."""
    parser = argparse.ArgumentParser(
        description="Compare reimplementation layouts against originals"
    )
    parser.add_argument("--ground-truth", default="eval_output/ground_truth")
    parser.add_argument("--reimpl", default="eval_output/reimpl_layouts")
    parser.add_argument("--output", default="eval_output/reimpl_comparison")
    parser.add_argument("--max-graphs", type=int, default=0)
    args = parser.parse_args()

    compare_all(
        gt_dir=Path(args.ground_truth),
        reimpl_dir=Path(args.reimpl),
        output_dir=Path(args.output),
        max_graphs=args.max_graphs,
    )


if __name__ == "__main__":
    main()
