"""Verify d3-force pipeline fidelity against the Node reference adapter."""

from __future__ import annotations

import argparse
import json
import random
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List, Sequence, Tuple

import torch

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from dagua.eval.competitors.d3force_competitor import D3ForceCompetitor  # noqa: E402
from dagua.eval.equivalence_metrics import anisotropic_procrustes, procrustes_rmsd  # noqa: E402
from dagua.graph import DaguaGraph  # noqa: E402
from dagua.layout.ops.d3force import (  # noqa: E402
    d3force_lcg_values,
    d3force_phyllotaxis_positions,
)
from dagua.layout.ops.pipelines.d3force import layout_d3force_pipeline  # noqa: E402

DEFAULT_CACHE = ROOT / "tests" / "fixtures" / "d3force_reference_layouts.json"
DEFAULT_REPORT = ROOT / "docs" / "algorithms" / "d3force_fidelity.md"
BIT_EXACT_THRESHOLD = 1.0e-9
CLOSE_THRESHOLD = 0.1
DEFAULT_SEED = 1
DEFAULT_TICKS = 300


def _graph_from_edges(name: str, num_nodes: int, edges: Sequence[Tuple[int, int]]) -> DaguaGraph:
    """Build one deterministic verification graph.

    Parameters
    ----------
    name : str
        Graph name used as a label prefix.
    num_nodes : int
        Number of nodes.
    edges : sequence[tuple[int, int]]
        Edge pairs.

    Returns
    -------
    DaguaGraph
        Graph with explicit nodes ``0..N-1``.
    """
    graph = DaguaGraph()
    for node in range(num_nodes):
        graph.add_node(node, label=f"{name}_{node}")
    for source, target in edges:
        graph.add_edge(source, target)
    graph.compute_node_sizes()
    return graph


def _random_dag_edges(num_nodes: int, edge_count: int, seed: int) -> List[Tuple[int, int]]:
    """Generate deterministic DAG edges.

    Parameters
    ----------
    num_nodes : int
        Number of nodes.
    edge_count : int
        Requested edge count.
    seed : int
        Python RNG seed.

    Returns
    -------
    list[tuple[int, int]]
        Sampled source-before-target edges.
    """
    candidates = [
        (source, target) for source in range(num_nodes) for target in range(source + 1, num_nodes)
    ]
    rng = random.Random(seed)
    return sorted(rng.sample(candidates, min(edge_count, len(candidates))))


def _verification_graphs() -> List[Tuple[str, DaguaGraph]]:
    """Build the small-first d3-force verification corpus.

    Returns
    -------
    list[tuple[str, DaguaGraph]]
        Named graphs used for fidelity reporting.
    """
    binary_tree = [(node, 2 * node + child) for node in range(5) for child in (1, 2)]
    grid = [(row * 5 + column, row * 5 + column + 1) for row in range(5) for column in range(4)] + [
        (row * 5 + column, (row + 1) * 5 + column) for row in range(4) for column in range(5)
    ]
    org_chart = [(0, node) for node in range(1, 6)] + [
        (manager, 6 + (manager - 1) * 2 + child) for manager in range(1, 6) for child in range(2)
    ]
    org_chart_deep: List[Tuple[int, int]] = []
    previous = [0]
    next_node = 1
    for width in (3, 5, 10, 20, 40):
        current = list(range(next_node, next_node + width))
        next_node += width
        for index, child in enumerate(current):
            org_chart_deep.append((previous[index % len(previous)], child))
        previous = current
    cases = [
        ("single_node", 1, []),
        ("small_chain", 6, [(node, node + 1) for node in range(5)]),
        ("binary_tree", 11, binary_tree),
        ("diamond", 4, [(0, 1), (0, 2), (1, 3), (2, 3)]),
        ("grid_5x5", 25, grid),
        ("org_chart_small", 16, org_chart),
        ("long_skip", 5, [(0, 1), (1, 2), (2, 3), (3, 4), (0, 3), (1, 4)]),
        ("disconnected", 5, [(0, 1), (2, 3)]),
        ("cycle_4", 4, [(0, 1), (1, 2), (2, 3), (3, 0)]),
        ("random_dag_50", 50, _random_dag_edges(50, 90, seed=4101)),
        ("org_chart_deep", 79, org_chart_deep),
    ]
    return [(name, _graph_from_edges(name, num_nodes, edges)) for name, num_nodes, edges in cases]


def _node_lcg_values(count: int = 20) -> List[float]:
    """Return LCG values generated by a tiny Node reference script.

    Parameters
    ----------
    count : int, default=20
        Number of values to generate.

    Returns
    -------
    list[float]
        Node-generated LCG sequence.
    """
    script = f"""
let s = 1;
const a = 1664525, c = 1013904223, m = 4294967296;
const vals = [];
for (let i = 0; i < {count}; ++i) {{
  s = (Math.imul(a, s) + c) >>> 0;
  vals.push(s / m);
}}
process.stdout.write(JSON.stringify(vals));
"""
    result = subprocess.run(["node", "-e", script], capture_output=True, text=True, check=True)
    return [float(value) for value in json.loads(result.stdout)]


def _cache_reference_layouts(path: Path, refresh: bool) -> Dict[str, Any]:
    """Load or create d3-force reference layouts.

    Parameters
    ----------
    path : pathlib.Path
        JSON cache path.
    refresh : bool
        Whether to discard the existing cache.

    Returns
    -------
    dict[str, Any]
        Reference payload.

    Raises
    ------
    RuntimeError
        If d3-force is unavailable or a reference layout fails.
    """
    if path.exists() and not refresh:
        return json.loads(path.read_text())
    competitor = D3ForceCompetitor()
    if not competitor.available():
        raise RuntimeError("d3-force is not available to Node.")
    rows: List[Dict[str, Any]] = []
    for name, graph in _verification_graphs():
        result = competitor.layout_with_variant(
            graph,
            seed=DEFAULT_SEED,
            variant_params={"ticks": DEFAULT_TICKS},
        )
        if result.pos is None:
            raise RuntimeError(f"d3-force reference failed for {name}: {result.error}")
        edges = graph.edge_index.t().tolist() if graph.edge_index.numel() else []
        rows.append(
            {
                "name": name,
                "num_nodes": graph.num_nodes,
                "edges": edges,
                "reference_positions": result.pos.tolist(),
            }
        )
    payload = {
        "reference": "d3-force",
        "seed": DEFAULT_SEED,
        "ticks": DEFAULT_TICKS,
        "layouts_per_graph": 1,
        "graphs": rows,
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2) + "\n")
    return payload


def _edge_index(edges: List[List[int]]) -> torch.Tensor:
    """Convert cached edge pairs to edge-index tensor.

    Parameters
    ----------
    edges : list[list[int]]
        Cached ``[source, target]`` pairs.

    Returns
    -------
    torch.Tensor
        Long tensor with shape ``[2, E]``.
    """
    if not edges:
        return torch.empty((2, 0), dtype=torch.long)
    return torch.tensor(edges, dtype=torch.long).t().contiguous()


def _evaluate(cache: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Evaluate pipeline residuals against cached references.

    Parameters
    ----------
    cache : dict[str, Any]
        Reference cache payload.

    Returns
    -------
    list[dict[str, Any]]
        Per-graph residual rows.
    """
    rows: List[Dict[str, Any]] = []
    for graph in cache["graphs"]:
        actual = layout_d3force_pipeline(
            edge_index=_edge_index(graph["edges"]),
            num_nodes=int(graph["num_nodes"]),
            seed=int(cache["seed"]),
            ticks=int(cache["ticks"]),
        )
        reference = torch.tensor(graph["reference_positions"], dtype=torch.float64)
        residual = procrustes_rmsd(actual.numpy(), reference.numpy())
        anisotropic = anisotropic_procrustes(actual.numpy(), reference.numpy())
        rows.append(
            {
                "name": graph["name"],
                "residual": float(residual),
                "anisotropic_residual": float(anisotropic["anisotropic_rmsd"]),
                "tier": "bit-exact"
                if residual < BIT_EXACT_THRESHOLD
                else ("close" if residual < CLOSE_THRESHOLD else "distributional"),
            }
        )
    return rows


def _write_report(path: Path, rows: List[Dict[str, Any]], lcg_match: bool) -> None:
    """Write the d3-force fidelity markdown report.

    Parameters
    ----------
    path : pathlib.Path
        Report destination.
    rows : list[dict[str, Any]]
        Per-graph residual rows.
    lcg_match : bool
        Whether Python and Node LCG values matched exactly.

    Returns
    -------
    None
        The report is written to disk.
    """
    bit_exact = sum(row["tier"] == "bit-exact" for row in rows)
    close = sum(row["tier"] == "close" for row in rows)
    distributional = len(rows) - bit_exact - close
    lines = [
        "# d3-force Fidelity",
        "",
        "Reference: `d3-force` via `dagua.eval.competitors.d3force_competitor.D3ForceCompetitor`.",
        f"Seed: `{DEFAULT_SEED}`. Ticks: `{DEFAULT_TICKS}`.",
        "",
        "LCG verification: "
        f"{'bit-for-bit match' if lcg_match else 'FAILED'} for the first 20 values.",
        "",
        f"Summary: {bit_exact} bit-exact, {close} close, {distributional} distributional.",
        "",
        "| graph | Procrustes d_R | anisotropic d_R | tier |",
        "| --- | ---: | ---: | --- |",
    ]
    for row in rows:
        lines.append(
            f"| {row['name']} | {row['residual']:.12g} | "
            f"{row['anisotropic_residual']:.12g} | {row['tier']} |"
        )
    lines.extend(
        [
            "",
            "Named residual: full-layout divergence first appears at the many-body force stage.",
            "The current native op matches d3-force's LCG, phyllotaxis initialization, link force,",
            "center force, and velocity-Verlet order, but uses direct ordered-pair n-body",
            "evaluation instead of d3-quadtree Barnes-Hut traversal. This is a mathematical",
            "summation/approximation-order gap, not runtime delegation.",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n")


def main() -> None:
    """Run d3-force fidelity verification.

    Returns
    -------
    None
        Prints per-graph residuals and writes the markdown report.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--refresh", action="store_true", help="Regenerate Node reference cache.")
    parser.add_argument("--cache", type=Path, default=DEFAULT_CACHE)
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT)
    args = parser.parse_args()

    node_lcg = _node_lcg_values(20)
    python_lcg = d3force_lcg_values(seed=DEFAULT_SEED, count=20)
    lcg_match = node_lcg == python_lcg
    phyllotaxis = d3force_phyllotaxis_positions(6)
    if not torch.isfinite(phyllotaxis).all():
        raise RuntimeError("d3-force phyllotaxis initialization produced non-finite values.")

    cache = _cache_reference_layouts(args.cache, refresh=args.refresh)
    rows = _evaluate(cache)
    _write_report(args.report, rows, lcg_match)

    bit_exact = sum(row["tier"] == "bit-exact" for row in rows)
    close = sum(row["tier"] == "close" for row in rows)
    distributional = len(rows) - bit_exact - close
    print(f"LCG first-20 match: {lcg_match}")
    for row in rows:
        print(
            f"{row['name']}: d_R={row['residual']:.12g} "
            f"anisotropic={row['anisotropic_residual']:.12g} tier={row['tier']}"
        )
    print(f"bit_exact={bit_exact} close={close} distributional={distributional}")
    print("first_divergent_stage=many_body_barnes_hut_vs_direct")


if __name__ == "__main__":
    main()
